### ISSUE TITLE
Close custom gateway window on "Enter" and save custom gateway on reload

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics.app#128]
![image](https://github.com/airalab/dapp.robonomics.network/assets/34866682/273746d1-4e93-4a48-a3e0-0f9da6061f4c)

**Comment by positivecrash** [comment]
@vol4tim Саша, смотри когда введен гейтвей кастомный, меняется переменная store.state.robonomicsUIvue.ipfs.activegateway

сможешь обработать на своей стороне релоад?

**Comment by vol4tim** [comment]
Добавил перезагрузку страницы при смене гейтвея. https://github.com/airalab/robonomics.app/commit/13050358f9ab59b636a7e443ba405ad78a64f6a0
