### ISSUE TITLE
Dapp only checks balance on first entry

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics.app#135]
![image](https://github.com/airalab/robonomics.app/assets/34866682/bab7ff34-82ae-4ca2-a89b-c49b8fd3cd80)
This page stated I had no XRT until page refresh (I've bought XRT after entering the page)

**Comment by PaTara43** [comment]
not fixed

**Comment by nakata5321** [comment]
Problem still exist on dev Dapp commit 0e4836b
![Screenshot_20240723_162750](https://github.com/user-attachments/assets/32bc3aa4-c3b0-41bf-9732-5007f1ad8e5f)

**Comment by nakata5321** [comment]
Fixed/ not actual at commit https://github.com/airalab/robonomics.app/commit/24120c0c9a5d51c67d620cfe2bf4def7a6ea0248
