### ISSUE TITLE
Got redirected back to parachain from libp2p 50% of the time on parachain to libp2p switch

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics.app#137]
![image](https://github.com/airalab/robonomics.app/assets/34866682/97112eba-282e-4e2f-bdb4-71254bd6f18a)

**Comment by vol4tim** [comment]
Describe what needs to be done so that I can reproduce this problem myself.

**Comment by PaTara43** [comment]
perhaps, this may have something to do with stacks issue

**Comment by PaTara43** [comment]
libp2p proxy restart helped

**Comment by positivecrash** [comment]
@PaTara43 @vol4tim can we close this issue or you have something to fix?

**Comment by vol4tim** [comment]
NO_RESERVATION error is caused by the fact that relay does not have a connection to proxy. Most likely, proxy disconnected from relay for some reason.
