### ISSUE TITLE
Can't loag config

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics.app#152]
Sometimes get this error and can't load telemetry
![image](https://github.com/airalab/robonomics.app/assets/55352168/50a0cfcf-6aac-47e2-a953-e78cc5ebd28f)

![image](https://github.com/airalab/robonomics.app/assets/55352168/cc2f5d4f-677f-4cf0-ba56-25f06cdf8691)

Last Dapp release.
Brave browser.

**Comment by vol4tim** [comment]
Added error handling https://github.com/airalab/robonomics.app/commit/8bf235623babf3a44e3edd01ae12a2becd97749b.
Need more information. Controller address and twin id. Now this information can be viewed in the logs.

**Comment by nakata5321** [comment]
no additional information provided since opened. suppose problem is outdated. Close issue.
