### ISSUE TITLE
asynchronous loading From IPFS

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics.app#161]
## Problem
Right now we have The IPFS gateway list and user can choose one IPFS gateway from the list. Sometimes the chosen gateway fall with error. examples can be found here - #159 #160 

## Proposal
Can we download data from all gateways in asynchronous way? And provide to the user data which will be downloaded first.

**Comment by vol4tim** [comment]
https://github.com/airalab/robonomics.app/commit/230d0da08e538d848460ede16eb0bad4f745fc21
