### ISSUE TITLE
USERS IN SUBSCRIPTION - duplicate addresses

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics.app#162]
# Problem
 Dapp don't react properly if the user adds an address to the subscription that is already there.

## How to reproduce

Open Dapp (tested on b4c699b) and go inside rws setup page. Copy address of any user in subscription and add this address to "add a user" field. press buton to add user to subscription. 
![image](https://github.com/user-attachments/assets/6c4180ae-e921-4266-8ae8-a0c8db9eefcb)

You will see that address added tu subscription(dapp don't ever ask to sign message to blockchain)
![image](https://github.com/user-attachments/assets/40b99f2d-f559-472a-bcb6-866a4415eaff)

and after few second address will diapers from dapp

![image](https://github.com/user-attachments/assets/d73c140c-babe-4563-9243-62ec7b935e7b)

**Comment by PaTara43** [comment]
still actual 421bcb719d6ac739db89c01a686600021dcc6a77

**Comment by vol4tim** [comment]
Fix b38729fb70e3d9ed8037844e323b25475596cff9
