### ISSUE TITLE
Can't buy/update subscription

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics.app#166]
Today i wanted to update my home subscription. when i started the process, i've got next error:
![image](https://github.com/user-attachments/assets/e4045a16-d7eb-45f4-97fe-3dc2ef2d33b3)

However, i'm sure that i have tokens on this account:

![image](https://github.com/user-attachments/assets/ad1bb038-8ba7-4da3-9fab-27dc12ea4e33)

in console logs i see next errors:

![image](https://github.com/user-attachments/assets/dc24075b-632a-4304-a2d5-319b210822c8)

Working on https://robonomics.app/

**Comment by vol4tim** [comment]
Fix https://github.com/airalab/robonomics.app/commit/39ed7ed36dccc0d795c2746f2c42f7fd7b790b2d
