### ISSUE TITLE
Can't add user to subscription

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics.app#167]
Tested on https://dev.robonomics.app/#/rws-setup with commit - `Build version: master v0.8.0 bb57edc`. Tested in Brave browser.

I'm trying to add user to subscription. However i've got next error:

![image](https://github.com/user-attachments/assets/711bf681-42c5-4280-832a-848c3063b339)

Console show me next:
![image](https://github.com/user-attachments/assets/50388985-9ae3-46fc-9e17-3a0a27684a56)

**Comment by PaTara43** [comment]
Same on chrome
![image](https://github.com/user-attachments/assets/2a423934-62e6-40ac-8a75-64ad13b70cad)
![image](https://github.com/user-attachments/assets/73b20470-20fd-4f61-85be-ef159a50e63a)

**Comment by LoSk-p** [comment]
I have different error in Firefox browser, owner has RWS token
![image](https://github.com/user-attachments/assets/424910ea-dd95-4e8b-8795-bb4514bf740d)
```
TypeError: t.freeWeight is undefined
    d useSubscription.js:94
    r useSend.js:21
    i useSend.js:52
    l RwsSetup.vue:74
    o runtime-core.esm-bundler.js:193
    s runtime-core.esm-bundler.js:201
    M runtime-core.esm-bundler.js:714
    u index.es.js:8432
    r runtime-dom.esm-bundler.js:1435
    o runtime-core.esm-bundler.js:193
    s runtime-core.esm-bundler.js:201
    n runtime-dom.esm-bundler.js:672
    ```

**Comment by vol4tim** [comment]
Fix https://github.com/airalab/robonomics.app/commit/36c75431e4955b5c222eeab9323c7eb620da9daa
