### ISSUE TITLE
trying to buy subscription for a fresh new account while having running subscriptions results in gui fail

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics.app#168]
![image](https://github.com/user-attachments/assets/06c7b14f-3b03-4845-b859-cc1320830e05)
and then I chose a freshly created account
![image](https://github.com/user-attachments/assets/ecb03bbc-15be-4137-a6f4-a7914a7ae1d8)
all the same

**Comment by PaTara43** [comment]
btw i can't click renew button. Had to remove other accounts from extensions

**Comment by PaTara43** [comment]
this resulted in infinite loading

**Comment by nakata5321** [comment]
@PaTara43 where do you test-  https://dev.robonomics.app/#/ or https://robonomics.app/#/ ?
If https://robonomics.app/#/ , then check again please, this night was new release on it.

**Comment by PaTara43** [comment]
same
