### ISSUE TITLE
Link "Guide to start" doesn't work

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics.app#169]
Hello! The link "Guide to start" on the main page https://robonomics.app/#/ doesn't work. It leads to 404 page 

<img width="504" alt="Screenshot 2024-10-01 at 12 48 20 PM" src="https://github.com/user-attachments/assets/5f50c244-0187-449e-97d4-5fe6c27a1128">

<img width="1299" alt="Screenshot 2024-10-01 at 12 49 08 PM" src="https://github.com/user-attachments/assets/2a3eb49e-50d6-43e3-ba9a-3eed35640b5a">

**Comment by vol4tim** [comment]
Fix https://github.com/airalab/robonomics.app/commit/fbec8641d59495b297d5312759982b4f6a8b652c
