### ISSUE TITLE
can't renew subscription

### ISSUE THREAD

**Issue by tubleronchik** [airalab/robonomics.app#171]
I opened the dApp and attempted to renew my subscription. However, I encountered the following issue:  `Subscription can not be activated due to unsuffcicient XRT balance`, even though my account had enough balance. 
The issue was resolved after reloading the `#/rws-buy` page.

Step to reproduce:

1. Open the dApp 
2. Navigate to `/#/rws-setup`
3. Click the refresh button to be redirected to `#/rws-buy`
4. Click on `renew subscription`
![image](https://github.com/user-attachments/assets/4540fc63-25cc-46aa-84ca-df45bef48083)

**Comment by nakata5321** [comment]
I have the same problem when repeat the same steps. No errors in console
![image](https://github.com/user-attachments/assets/f8e8b6e0-e524-4050-be65-a460a051b9cd)


Tested on https://github.com/airalab/robonomics.app/commit/421bcb719d6ac739db89c01a686600021dcc6a77

How ever, it's happens even if you want to renew subscription from main menu.

main screen:
![image](https://github.com/user-attachments/assets/c5a6a4e3-215b-4eed-8a71-d6873578d9b2)

then press "update button" and at the page `#/rws-buy` have same problem:
![image](https://github.com/user-attachments/assets/c442d9da-d332-4e3d-9c99-0ef972e755ff)

**Comment by vol4tim** [comment]
Fix 4a3767766aaa8d90bb59e9cfe0add325f996e1dc
