### ISSUE TITLE
[BUG] Critical! Sub json not downloaded

### ISSUE THREAD

**Issue by PaTara43** [airalab/robonomics.app#175]
**1. Development/Production**
both

**2. Page Address**
/rws-setup

**3. Error Info/Story**
When I set a fully new subscription, add name, owner address and generate a controller's account, I only get it's json export file. Not the subscription backup file to get uploaded to integration later. And, ofc, when downloading subscription backup file controller is re-generated.
![image](https://github.com/user-attachments/assets/07df7e65-4fed-4435-bb1d-30b59a69e63f)

**4. Expected behavior**
Download both files

**5. Console logs**
![image](https://github.com/user-attachments/assets/c3d18bcd-b19b-4536-97ac-55000aa5bb3a)

**6. Context**
Browser: Firefox
Dapp release: 421bcb719d6ac739db89c01a686600021dcc6a77

**Comment by PaTara43** [comment]
Also, it should be taken into consideration, that the blocks should be aligned in a way that the user fills in pinata creds/ipfs gateway info before actually generating controller seed and thus getting backup file

**Comment by positivecrash** [comment]
You should tap on "backup" -> "for server" to get both files
